CREATE TABLE IF NOT EXISTS t_user_tts_history (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    uid INT NOT NULL COMMENT '用户ID',
    input_text TEXT NULL COMMENT '输入文本',
    emotion VARCHAR(32) DEFAULT 'neutral' COMMENT '情绪参数',
    language VARCHAR(32) DEFAULT 'zh-cn' COMMENT '语言参数',
    requested_format VARCHAR(16) DEFAULT 'wav' COMMENT '前端请求的输出格式',
    source_bucket VARCHAR(128) DEFAULT NULL COMMENT '参考音频 bucket',
    source_object VARCHAR(255) DEFAULT NULL COMMENT '参考音频对象路径',
    source_filename VARCHAR(255) DEFAULT NULL COMMENT '参考音频文件名',
    source_content_type VARCHAR(128) DEFAULT NULL COMMENT '参考音频 content-type',
    source_file_size BIGINT DEFAULT 0 COMMENT '参考音频大小',
    result_bucket VARCHAR(128) DEFAULT NULL COMMENT '生成音频 bucket',
    result_object VARCHAR(255) DEFAULT NULL COMMENT '生成音频对象路径',
    result_filename VARCHAR(255) DEFAULT NULL COMMENT '生成音频文件名',
    result_content_type VARCHAR(128) DEFAULT NULL COMMENT '生成音频 content-type',
    result_file_size BIGINT DEFAULT 0 COMMENT '生成音频大小',
    status VARCHAR(32) DEFAULT 'PENDING' COMMENT '处理状态',
    raw_result TEXT NULL COMMENT 'Python 服务返回元信息',
    error_message VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_t_user_tts_history_uid (uid),
    KEY idx_t_user_tts_history_create_time (create_time)
) COMMENT='用户文字转语音历史表';
