CREATE TABLE IF NOT EXISTS t_user_meeting_note (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    uid INT NOT NULL COMMENT '用户ID',
    title VARCHAR(128) NOT NULL COMMENT '纪要标题',
    scene_type VARCHAR(32) NOT NULL DEFAULT 'meeting' COMMENT '场景类型 meeting/classroom',
    selected_speaker_ids_json TEXT NULL COMMENT '预留：已选发言人ID列表',
    raw_bucket VARCHAR(128) DEFAULT NULL COMMENT '原始音频 bucket',
    raw_object VARCHAR(255) DEFAULT NULL COMMENT '原始音频对象路径',
    raw_filename VARCHAR(255) DEFAULT NULL COMMENT '原始音频文件名',
    raw_content_type VARCHAR(128) DEFAULT NULL COMMENT '原始音频 content-type',
    raw_file_size BIGINT DEFAULT 0 COMMENT '原始音频大小',
    full_transcript LONGTEXT NULL COMMENT '全文转写',
    summary_text TEXT NULL COMMENT '摘要内容',
    keywords_json TEXT NULL COMMENT '关键词列表 JSON',
    todo_json TEXT NULL COMMENT '待办事项列表 JSON',
    raw_result LONGTEXT NULL COMMENT 'ASR 原始响应',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '处理状态',
    error_message VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_t_user_meeting_note_uid (uid),
    KEY idx_t_user_meeting_note_scene_type (scene_type),
    KEY idx_t_user_meeting_note_create_time (create_time)
) COMMENT='用户智能纪要任务表';
