CREATE TABLE IF NOT EXISTS t_user_voiceprint_history (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    uid INT NOT NULL COMMENT '用户ID',
    left_bucket VARCHAR(128) DEFAULT NULL COMMENT '左侧音频 bucket',
    left_object VARCHAR(255) DEFAULT NULL COMMENT '左侧音频对象路径',
    left_filename VARCHAR(255) DEFAULT NULL COMMENT '左侧音频文件名',
    left_content_type VARCHAR(128) DEFAULT NULL COMMENT '左侧音频 content-type',
    left_file_size BIGINT DEFAULT 0 COMMENT '左侧音频大小',
    right_bucket VARCHAR(128) DEFAULT NULL COMMENT '右侧音频 bucket',
    right_object VARCHAR(255) DEFAULT NULL COMMENT '右侧音频对象路径',
    right_filename VARCHAR(255) DEFAULT NULL COMMENT '右侧音频文件名',
    right_content_type VARCHAR(128) DEFAULT NULL COMMENT '右侧音频 content-type',
    right_file_size BIGINT DEFAULT 0 COMMENT '右侧音频大小',
    score DECIMAL(10, 4) DEFAULT NULL COMMENT '相似度得分',
    threshold_value DECIMAL(10, 4) DEFAULT NULL COMMENT '判定阈值',
    same_person TINYINT(1) DEFAULT NULL COMMENT '是否同一人',
    result_message VARCHAR(255) DEFAULT NULL COMMENT '结果描述',
    status VARCHAR(32) DEFAULT 'PENDING' COMMENT '处理状态',
    raw_result TEXT NULL COMMENT 'Python 服务原始响应',
    error_message VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_t_user_voiceprint_history_uid (uid),
    KEY idx_t_user_voiceprint_history_create_time (create_time)
) COMMENT='用户声纹比对历史表';
